# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Week3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Week3
  pod 'RealmSwift', '~>10'
end
